train:
  log_interval: 500
  eval_interval: 5000
  seed: 1234
  epochs: 10000
  learning_rate: 0.0002
  betas: [0.8, 0.99]
  eps: 1.0e-09
  batch_size: 64
  fp16_run: true
  lr_decay: 0.999875
  segment_size: 8192
  init_lr_ratio: 1
  warmup_epochs: 0
  c_mel: 45
  c_kl_text: 0 # default: 0
  c_kl_dur: 2 # default: 2
  c_kl_audio: 0.05 # 0.05 Allow more audio variation. default: 1

data:
  training_files: datasets/madasr23_base/filelists/train.txt
  validation_files: datasets/madasr23_base/filelists/val.txt
  vocab_file: datasets/madasr23_base/vocab.txt
  text_cleaners:
    - phonemize_text
    - add_spaces
    - tokenize_text
    - add_bos_eos
  cleaned_text: true
  language: bn
  bits_per_sample: 16
  sample_rate: 16000
  n_fft: 2048
  hop_length: 256
  win_length: 1024
  n_mels: 80 # 100 works better with "slaney" mel-transform. default: 80
  f_min: 0
  f_max:
  n_speakers: 2011
  use_mel: true

model:
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
  n_heads: 2
  n_layers: 6
  n_layers_q: 12 # default: 16
  n_flows: 8 # default: 4
  kernel_size: 3
  p_dropout: 0.1
  speaker_cond_layer: 3 # 0 to disable speaker conditioning
  resblock: "1"
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  upsample_rates: [8, 8, 2, 2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [16, 16, 4, 4]
  mas_noise_scale: 0.01 # 0.0 to disable Gaussian noise in MAS
  mas_noise_scale_decay: 2.0e-06
  use_spectral_norm: false
  use_transformer_flow: false
  gin_channels: 256
